### ISSUE TITLE
Exceptions from the system under test should not be allowed to stop testify

### ISSUE THREAD

**Issue by bukzor** [Yelp/Testify#176]
If a function under test raises SystemExit  (or other similar exception), currently testify will stop, and (for example) will report "0 tests 0 failures".

This is entirely incorrect.

When running a test we must catch all exceptions. If we see SystemExist (or KeyboartInterrupt, or similar) we must inspect its source. If it originates from the system under test, it should be caught and reported, and must not stop the testing session.

**Comment by asottile** [comment]
@bukzor  via #335
