### ISSUE TITLE
report test discovery as a failure

### ISSUE THREAD

**Issue by bukzor** [Yelp/Testify#279]
The aim is to enabling our test-reporting infrastructure to report discovery failures.
The implementation will look quite like what we did for class setup/teardown failures; add a dummy "discovery" test that passes or fails depending on whether discovery succeeds.

The prior art (in class setup failures) is found here:
https://github.com/Yelp/Testify/blob/master/testify/test_case.py#L222

**Comment by asottile** [comment]
This was really only relevant when using the sql reporter
