### ISSUE TITLE
testsuite failures in most versions

### ISSUE THREAD

**Issue by idella** [Yelp/Testify#283]
It appears it wants catbox installed for running the tetsuite yet I see no mention of it as a dep in the source.
Exception: Violation collection pipeline tests require catbox.
https://github.com/Yelp/catbox/wiki/Install-Catbox-with-PCRE-enabled

I get a whole lot of 

```python
ERROR    Could not remove broken import file /mnt/gen2/TmpDir/portage/dev-python/testify-0.3.6/work/testify-0.3.6/test/fake_broken_importynJXxe.pyc: OSError(2, 'No such file or directory')
.ERROR    Could not remove broken import file /mnt/gen2/TmpDir/portage/dev-python/testify-0.3.6/work/testify-0.3.6/test/fake_broken_importF_LPkF.pyc: OSError(2, 'No such file or directory')
.ERROR    test error message 2
```

No idea where these fake_broken_import..... files come from.  Not in the source repo.

Then a whole lot of

```python
E.........................................................ERROR    Could not remove broken import file /mnt/gen2/TmpDir/portage/dev-python/testify-0.3.6/work/testify-0.3.6/test/fake_broken_importDLsT2s.pyc: OSError(2, 'No such file or directory')
.........error: test.test_runner_server_test TestCaseFailureLimitClassTeardownErrorTestCase.test_methods_are_not_run_after_failure_limit_reached
Traceback (most recent call last):
  File "./test/test_runner_server_test.py", line 113, in teardown_server
    self.stop_server()
  File "./test/test_runner_server_test.py", line 100, in stop_server
    self.server.shutdown()
  File "/mnt/gen2/TmpDir/portage/dev-python/testify-0.3.6/work/testify-0.3.6-python2_7/lib/testify/test_runner_server.py", line 476, in shutdown
    if iol.running():
AttributeError: 'EPollIOLoop' object has no attribute 'running'
```

then it hangs

EERROR    Could not remove broken import file /mnt/gen2/TmpDir/portage/dev-python/testify-0.3.6/work/testify-0.3.6/test/fake_broken_importZoumnL.pyc: OSError(2, 'No such file or directory')
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
ERROR    No client activity for 10s, shutting down.
^X^Z
[13]+  Stopped                 ebuild testify-0.3.6.ebuild clean test

**Comment by asottile** [comment]
@idella testify 0.5.7 contains the fix for tornado
