### ISSUE TITLE
Give testify a new version

### ISSUE THREAD

**Issue by ealter** [Yelp/Testify#312]
After #293, let's give testify a new version so that we can integrate this change into yelp's codebase.

**Comment by bukzor** [comment]
I wanted to do some work on suite discovery before we go through the pain
of a rollout.

I'll try to get to it soon.

--phone is hard.

**Comment by asottile** [comment]
We've stopped doing expensive rollout with 0.6.0 at yelp (we've stopped
bumping the system version). I think release is not a big deal since it's
all virtualenv 'd

Phone is also hard

**Comment by ealter** [comment]
The reason I want to give this a version number is so that I can make
yelp-main compatible with testify-master (since the most recent change is
not backwards compatible).

I'd like to get started on my work with factories, but I can't do that
until testify has the addfinalizer function (assuming that my pull request
is approved). I can't add that function until yelp-main is compatible with
the current master of Testify.

**Comment by bukzor** [comment]
Ah, true. In that case, disregard my comment and go for it.

--phone is hard.

**Comment by asottile** [comment]
#313
