### ISSUE TITLE
testify should namespace its imports (especially plugins/profile)

### ISSUE THREAD

**Issue by struys** [Yelp/Testify#342]
@bukzor's notes on this:

First, testify imports all of its plugins without namespace qualification. One of these plugins is named 'profile.py'. After that, there is a 'profile' entry in sys.modules pointing to that file. Later, when hotshot tries to import the stdlib profile.py, it gets the wrong thing and explodes.
Second, the trigger for the difference between my branch and master was this additional code, in yelp/testing/_init_.py
This make pydoc yelp.testing work right.
_all_ = locals().keys()
_all is the controller for what happens when you do from yelp.testing import *. If there is no __all_, you get all global variables defined in the module; which is to say, this is an explicit version of what was already going on. I actually confirmed that running from yelp.testing import * did the same thing on my branch and master, and it does. I think testify saw this and got quite confused somehow, since the below bug manifested when it was trying to import yelp.tests.util.protovis_test.servletbench, which is not a thing."
buck describes a solution:
"The usual name of /usr/lib/python2.6/dist-packages/testify/plugins/profile.py would be testify.plugins.profile. Instead, testify adds that directory to the sys.path, and imports profile. It would be better to import it with the fully-qualified name, or to remove it from the sys.modules after it has what it wants, so as to not collide with the legitimate profile module.
Testify does quite a bit of logic based on what it finds during discovery. This went awry with what should have been a no-op operation to _all_. For more information, see the long line of spaghetti code at "/usr/lib/python2.6/dist-packages/testify/test_discovery.py", line 57

Since testify only uses the plugins' module-objects, and doesn't try to import them in the "normal way", I think it's quite valid to just delete the sys.modules entry after doing the import-by-name. Also, I can't think of a general-purpose way to calculate the most-qualified name for plugins on the TESTIFY-PLUGINS path.
It would look at bit like this:
{{
{#!python import sys plugins = [] for plugin in plugin_paths: plugin_name = strip_ext(basename(plugin)) # Don't get confused if somehting by that name is already imported orig_module = sys.modules.get(plugin_name) sys.path.insert(0, plugin_dir(plugin)) plugins.append(__import__(plugin_name)) del sys.path[0] if orig_module is None: del sys.modules[plugin_name(plugin)] else: sys.modules[plugin_name(plugin)] = orig_module }}
}

**Comment by asottile** [comment]
I'm wondering why /usr/lib/python2.6 got involved at all.  We don't use the system installed testify.

The formatting of this post also is broken :(

**Comment by asottile** [comment]
Though the issue text is a mess. This is done as I understand it:

https://github.com/Yelp/Testify/blob/335f04a7de583026a1e0d04d006f4c40524fd89d/testify/test_program.py#L66-L72

Relevant PR: https://github.com/Yelp/Testify/pull/303

**Comment by struys** [comment]
@asottile thanks for digging into it.

I attempted to clean up the issue text a bit just so we have a record of the historical problem, @bukzor let me know if it doesn't make sense anymore.
